# -*- coding: utf-8 -*-
"""Fachliche Freigabe der Eigenregeln des Cyber-Typs, an denen kein
Klärungspunkt hing (Excel GBU_Cyber_Regelpruefung, Blätter „Muster" und
„Regeln"). Wird von apply_cy_regelpruefung.py aus der zurückgegebenen Excel
geschrieben; gen_cy_catalog.py setzt freigegebene Regeln auf VERIFIED.

Format: Regel-Code -> (Entscheidung, Korrektur)
Entscheidung: 'Freigeben' | 'Ändern' | 'Streichen'.
Muster-Entscheidungen (M1…M6) werden beim Übernehmen auf die zugehörigen
Regeln aller Komponenten ausgerollt; eine Zeile im Blatt „Regeln" mit
eigener Entscheidung geht vor.

Solange eine Regel hier fehlt, bleibt sie REVIEW_REQUIRED. „Ändern" und
„Streichen" werden NICHT automatisch umgesetzt – sie sind im Inhalt
(cy_content/*.py) nachzuziehen; bis dahin bleibt die Regel REVIEW_REQUIRED
und die Korrektur steht als Hinweis in den notes."""

DATUM = '2026-09-03'

FREIGABE = {
    'CY-C01-R7': ('Freigeben', ''),
    'CY-C01-R8': ('Freigeben', ''),
    'CY-C01-R9': ('Freigeben', ''),
    'CY-C01-R11': ('Freigeben', ''),
    'CY-C01-R12': ('Freigeben', ''),
    'CY-C01-R13': ('Freigeben', ''),
    'CY-C02-R5': ('Freigeben', ''),
    'CY-C02-R6': ('Freigeben', ''),
    'CY-C02-R7': ('Freigeben', ''),
    'CY-C02-R9': ('Freigeben', ''),
    'CY-C02-R10': ('Freigeben', ''),
    'CY-C02-R11': ('Freigeben', ''),
    'CY-C03-R7': ('Freigeben', ''),
    'CY-C03-R8': ('Freigeben', ''),
    'CY-C03-R9': ('Freigeben', ''),
    'CY-C03-R11': ('Freigeben', ''),
    'CY-C03-R12': ('Freigeben', ''),
    'CY-C03-R13': ('Freigeben', ''),
    'CY-C04-R7': ('Freigeben', ''),
    'CY-C04-R8': ('Freigeben', ''),
    'CY-C04-R9': ('Freigeben', ''),
    'CY-C04-R11': ('Freigeben', ''),
    'CY-C04-R12': ('Freigeben', ''),
    'CY-C04-R13': ('Freigeben', ''),
    'CY-C05-R7': ('Freigeben', ''),
    'CY-C05-R8': ('Freigeben', ''),
    'CY-C05-R9': ('Freigeben', ''),
    'CY-C05-R11': ('Freigeben', ''),
    'CY-C05-R12': ('Freigeben', ''),
    'CY-C05-R13': ('Freigeben', ''),
    'CY-C06-R7': ('Freigeben', ''),
    'CY-C06-R8': ('Freigeben', ''),
    'CY-C06-R9': ('Freigeben', ''),
    'CY-C06-R11': ('Freigeben', ''),
    'CY-C06-R12': ('Freigeben', ''),
    'CY-C06-R13': ('Freigeben', ''),
    'CY-C07-R7': ('Freigeben', ''),
    'CY-C07-R8': ('Freigeben', ''),
    'CY-C07-R9': ('Freigeben', ''),
    'CY-C07-R11': ('Freigeben', ''),
    'CY-C07-R12': ('Freigeben', ''),
    'CY-C07-R13': ('Freigeben', ''),
    'CY-C08-R7': ('Freigeben', ''),
    'CY-C08-R8': ('Freigeben', ''),
    'CY-C08-R9': ('Freigeben', ''),
    'CY-C08-R11': ('Freigeben', ''),
    'CY-C08-R12': ('Freigeben', ''),
    'CY-C08-R13': ('Freigeben', ''),
    'CY-C09-R7': ('Freigeben', ''),
    'CY-C09-R8': ('Freigeben', ''),
    'CY-C09-R9': ('Freigeben', ''),
    'CY-C09-R11': ('Freigeben', ''),
    'CY-C09-R12': ('Freigeben', ''),
    'CY-C09-R13': ('Freigeben', ''),
    'CY-C10-R7': ('Freigeben', ''),
    'CY-C10-R8': ('Freigeben', ''),
    'CY-C10-R9': ('Freigeben', ''),
    'CY-C10-R11': ('Freigeben', ''),
    'CY-C10-R12': ('Freigeben', ''),
    'CY-C10-R13': ('Freigeben', ''),
    'CY-C11-R3': ('Freigeben', ''),
    'CY-C11-R4': ('Freigeben', ''),
    'CY-C11-R5': ('Freigeben', ''),
    'CY-C12-R4': ('Freigeben', ''),
    'CY-C12-R5': ('Freigeben', ''),
    'CY-C12-R6': ('Freigeben', ''),
    'CY-C12-R7': ('Freigeben', ''),
    'CY-C13-R2': ('Freigeben', ''),
    'CY-C13-R3': ('Freigeben', ''),
    'CY-C13-R4': ('Freigeben', ''),
    'CY-C13-R5': ('Freigeben', ''),
    'CY-C14-R2': ('Freigeben', ''),
    'CY-C14-R3': ('Freigeben', ''),
    'CY-N01-R1': ('Freigeben', ''),
    'CY-N01-R2': ('Freigeben', ''),
    'CY-N01-R4': ('Freigeben', ''),
    'CY-N02-R3': ('Freigeben', ''),
    'CY-O01-R1': ('Freigeben', ''),
    'CY-O01-R2': ('Freigeben', ''),
    'CY-O01-R3': ('Freigeben', ''),
    'CY-O01-R4': ('Freigeben', ''),
    'CY-O02-R3': ('Freigeben', ''),
    'CY-O03-R3': ('Freigeben', ''),
    'CY-O04-R2': ('Freigeben', ''),
    'CY-O05-R2': ('Freigeben', ''),
    'CY-O05-R3': ('Freigeben', ''),
    'CY-O05-R4': ('Freigeben', ''),
    'CY-O05-R5': ('Freigeben', ''),
    'CY-O06-R2': ('Freigeben', ''),
    'CY-O07-R2': ('Freigeben', ''),
    'CY-O08-R1': ('Freigeben', ''),
    'CY-O08-R2': ('Freigeben', ''),
    'CY-Z01-R3': ('Freigeben', ''),
    'CY-Z01-R4': ('Freigeben', ''),
    'CY-Z04-R3': ('Freigeben', ''),
    'CY-Z04-R4': ('Freigeben', ''),
    'CY-Z05-R1': ('Freigeben', ''),
    'CY-Z05-R2': ('Freigeben', ''),
}
